// <auto-generated />
using System;
using MedicalBilling.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace MedicalBilling.Infrastructure.Data.Migrations
{
    [DbContext(typeof(HealthDbContext))]
    partial class HealthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MedicalBilling.Domain.Entities.Doctor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.Property<string>("Specialization").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.ToTable("Doctors");
            });

            modelBuilder.Entity("MedicalBilling.Domain.Entities.Patient", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("BirthDate").HasColumnType("datetime2");
                b.Property<string>("FullName").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                b.HasKey("Id");
                b.ToTable("Patients");
            });

            modelBuilder.Entity("MedicalBilling.Infrastructure.Data.Models.AppUser", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int?>("DoctorId").HasColumnType("int");
                b.Property<string>("PasswordHash").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Role").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Username").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.HasKey("Id");
                b.HasIndex("Username").IsUnique();
                b.ToTable("Users");
            });

            modelBuilder.Entity("MedicalBilling.Domain.Entities.Visit", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<int>("DoctorId").HasColumnType("int");
                b.Property<decimal>("Fee").HasPrecision(10, 2).HasColumnType("decimal(10,2)");
                b.Property<int>("PatientId").HasColumnType("int");
                b.Property<DateTime>("VisitDate").HasColumnType("datetime2");
                b.HasKey("Id");
                b.HasIndex("DoctorId");
                b.HasIndex("PatientId", "VisitDate").IsUnique();
                b.ToTable("Visits");
            });

            modelBuilder.Entity("MedicalBilling.Domain.Entities.Visit", b =>
            {
                b.HasOne("MedicalBilling.Domain.Entities.Doctor", "Doctor")
                    .WithMany("Visits").HasForeignKey("DoctorId")
                    .OnDelete(DeleteBehavior.Restrict).IsRequired();
                b.HasOne("MedicalBilling.Domain.Entities.Patient", "Patient")
                    .WithMany("Visits").HasForeignKey("PatientId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Doctor");
                b.Navigation("Patient");
            });

            modelBuilder.Entity("MedicalBilling.Domain.Entities.Doctor", b => { b.Navigation("Visits"); });
            modelBuilder.Entity("MedicalBilling.Domain.Entities.Patient", b => { b.Navigation("Visits"); });
#pragma warning restore 612, 618
        }
    }
}
