<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>GPWebAPIC_</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GPWebAPI.Application\GPWebAPI.Application.csproj" />
    <ProjectReference Include="..\GPWebAPI.Infrastructure\GPWebAPI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
