//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordleGameProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int ID_P { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public int ID_F { get; set; }
    }
}
